cellsociety_team05: simulations.Schelling Class Reference
simulations.Schelling Class Reference
Public Member Functions
Schelling (int game, int cellTypes, int size, int delay, int cellSides, List< Integer > params)
void nextGen (SceneUpdater updater)
boolean computeTorrodialHood (int row, int col)
boolean computeNeighbourhood (int row, int col)
String simTitle ()
HashMap< Integer, Integer > cellProportions ()
void setNewParams (HashMap< Integer, Integer > params)
Public Member Functions inherited from simulations.Sim
Sim (int sim, int cellTypes, int size, int delay, int cellSides, List< Integer > params)
void initMap ()
SimData getData ()
HashMap< Pair, Pair > getMap ()
List< Integer > getParameters ()
abstract void setNewParams (HashMap< Integer, Integer > params)
abstract void nextGen (SceneUpdater updater)
abstract String simTitle ()
abstract HashMap< Integer, Integer > cellProportions ()
Private Member Functions
void updateState (int row, int col, int[][] tempMap, List< Integer > emptyCells, SceneUpdater updater)
Private Attributes
int threshold
int blueTotal
int redTotal
Additional Inherited Members
Protected Member Functions inherited from simulations.Sim
List< Integer > getEmptyCells ()
void populate (int fill, int population, int size)
void setCell (int x, int y, int value)
int calculateTotal ()
Protected Attributes inherited from simulations.Sim
int sim
List< Integer > params
SimData gameData
int[][] map
int delay
int cellTypes
int size
int cellSides
int[][] neighbors
Random rand = new Random()
Detailed Description
Author
Kei Yoshikoshi, Nic Sab, MengChao Feng Simulates Schelling's Model of Segregation. Is able to update the 2-D array given some data and a set of rules
Definition at line 19 of file Schelling.java.
Constructor & Destructor Documentation
simulations.Schelling.Schelling (int game, int cellTypes, int size, int delay, int cellSides, List< Integer > params)
Parameters
game : Game type
cellTypes : how many types of cells
size : size of grid
delay : the FPS
cellSides : how many sides to each cell (polygon)
params : list of parameters that vary per simulation
Definition at line 39 of file Schelling.java.
Member Function Documentation
HashMap<Integer, Integer> simulations.Schelling.cellProportions ()
Returns
HashMap that contains the cell proportions
Definition at line 162 of file Schelling.java.
boolean simulations.Schelling.computeNeighbourhood (int row, int col)
Looks at the neighbors and returns whether is satisfied or not
Parameters
row
col
Returns
Definition at line 128 of file Schelling.java.
References simulations.Sim.cellSides, utility.Neighborhood.getNeighbors(), simulations.Sim.map, and simulations.Sim.neighbors.
boolean simulations.Schelling.computeTorrodialHood (int row, int col)
Computes neighborhood for the torroidal
Parameters
row
col
Returns
Definition at line 99 of file Schelling.java.
References utility.Neighborhood.getTorrodialNeighbors(), simulations.Sim.map, and simulations.Sim.neighbors.
Referenced by simulations.Schelling.nextGen().
void simulations.Schelling.nextGen (SceneUpdater updater)
Updates the next generation of cells
Definition at line 50 of file Schelling.java.
References simulations.Schelling.computeTorrodialHood(), utility.MapCopier.copyOfArray(), simulations.Sim.getEmptyCells(), simulations.Sim.map, and simulations.Schelling.updateState().
void simulations.Schelling.setNewParams (HashMap< Integer, Integer > params)
Sets the new parameters that the user changed during simulation
Parameters
Definition at line 175 of file Schelling.java.
String simulations.Schelling.simTitle ()
Title of the simulation
Definition at line 154 of file Schelling.java.
void simulations.Schelling.updateState (int row, int col, int tempMap[][], List< Integer > emptyCells, SceneUpdater updater) private
Takes in different parameters to update the state of a specific cell
Parameters
row
col
tempMap : a copy of the grid
emptyCells : list of empty cells
updater : SceneUpdater object
Definition at line 75 of file Schelling.java.
References simulations.Sim.map, and cellsociety_team05.SceneUpdater.updateScene().
Referenced by simulations.Schelling.nextGen().
Member Data Documentation
int simulations.Schelling.blueTotal private
Definition at line 21 of file Schelling.java.
int simulations.Schelling.redTotal private
Definition at line 22 of file Schelling.java.
int simulations.Schelling.threshold private
Definition at line 20 of file Schelling.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team05/repository/src/simulations/Schelling.java