cellsociety_team05: simulations.Life Class Reference
simulations.Life Class Reference
Public Member Functions
Life (int sim, int cellTypes, int size, int delay, int cellSides, List< Integer > params)
void nextGen (SceneUpdater updater)
String simTitle ()
HashMap< Integer, Integer > cellProportions ()
void setNewParams (HashMap< Integer, Integer > params)
Public Member Functions inherited from simulations.Sim
Sim (int sim, int cellTypes, int size, int delay, int cellSides, List< Integer > params)
void initMap ()
SimData getData ()
HashMap< Pair, Pair > getMap ()
List< Integer > getParameters ()
abstract void setNewParams (HashMap< Integer, Integer > params)
abstract void nextGen (SceneUpdater updater)
abstract String simTitle ()
abstract HashMap< Integer, Integer > cellProportions ()
Private Member Functions
int updateState (int row, int col)
int computeNeighbourhood (int row, int col)
Private Attributes
int aliveTotal
Additional Inherited Members
Protected Member Functions inherited from simulations.Sim
List< Integer > getEmptyCells ()
void populate (int fill, int population, int size)
void setCell (int x, int y, int value)
int calculateTotal ()
Protected Attributes inherited from simulations.Sim
int sim
List< Integer > params
SimData gameData
int[][] map
int delay
int cellTypes
int size
int cellSides
int[][] neighbors
Random rand = new Random()
Detailed Description
Definition at line 14 of file Life.java.
Constructor & Destructor Documentation
simulations.Life.Life (int sim, int cellTypes, int size, int delay, int cellSides, List< Integer > params)
Definition at line 17 of file Life.java.
Member Function Documentation
HashMap<Integer, Integer> simulations.Life.cellProportions ()
Definition at line 68 of file Life.java.
References simulations.Sim.calculateTotal().
int simulations.Life.computeNeighbourhood (int row, int col) private
Definition at line 50 of file Life.java.
References utility.Neighborhood.getTorrodialNeighbors(), simulations.Sim.map, and simulations.Sim.neighbors.
Referenced by simulations.Life.updateState().
void simulations.Life.nextGen (SceneUpdater updater)
Definition at line 22 of file Life.java.
References utility.MapCopier.copyOfArray(), simulations.Sim.map, simulations.Sim.size, cellsociety_team05.SceneUpdater.updateScene(), and simulations.Life.updateState().
void simulations.Life.setNewParams (HashMap< Integer, Integer > params)
Definition at line 75 of file Life.java.
String simulations.Life.simTitle ()
Definition at line 63 of file Life.java.
int simulations.Life.updateState (int row, int col) private
Definition at line 39 of file Life.java.
References simulations.Life.computeNeighbourhood(), and simulations.Sim.map.
Referenced by simulations.Life.nextGen().
Member Data Documentation
int simulations.Life.aliveTotal private
Definition at line 15 of file Life.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team05/repository/src/simulations/Life.java