cellsociety_team05: simulations.Sugar Class Reference
simulations.Sugar Class Reference
Public Member Functions
Sugar (int sim, int cellTypes, int size, int delay, int cellSides, List< Integer > params)
void initMap ()
void nextGen (SceneUpdater updater)
String simTitle ()
HashMap< Integer, Integer > cellProportions ()
void setNewParams (HashMap< Integer, Integer > params)
Public Member Functions inherited from simulations.Sim
Sim (int sim, int cellTypes, int size, int delay, int cellSides, List< Integer > params)
void initMap ()
SimData getData ()
HashMap< Pair, Pair > getMap ()
List< Integer > getParameters ()
abstract void setNewParams (HashMap< Integer, Integer > params)
abstract void nextGen (SceneUpdater updater)
abstract String simTitle ()
abstract HashMap< Integer, Integer > cellProportions ()
Public Attributes
int patchCap
Private Member Functions
void fillAgents (List< Integer > index)
void growSugar (SceneUpdater updater)
void updateAgent (SceneUpdater updater)
void updateHash (Map< Integer, Integer > changedAgents, Map< Integer, Agent > babies, SceneUpdater updater)
Private Attributes
int preset
Map< Integer, Agent > agents = new HashMap<Integer, Agent>()
int[] initSugar
int[] metabolism
int[] vision
int agentNum = 0
int growBack
int growInt
int worldAge = 0
int[] maxLife
int[] fertile
Additional Inherited Members
Protected Member Functions inherited from simulations.Sim
List< Integer > getEmptyCells ()
void populate (int fill, int population, int size)
void setCell (int x, int y, int value)
int calculateTotal ()
Protected Attributes inherited from simulations.Sim
int sim
List< Integer > params
SimData gameData
int[][] map
int delay
int cellTypes
int size
int cellSides
int[][] neighbors
Random rand = new Random()
Detailed Description
Definition at line 15 of file Sugar.java.
Constructor & Destructor Documentation
simulations.Sugar.Sugar (int sim, int cellTypes, int size, int delay, int cellSides, List< Integer > params)
Definition at line 29 of file Sugar.java.
References simulations.Sim.calculateTotal(), simulations.Sugar.fertile, and simulations.Sugar.maxLife.
Member Function Documentation
HashMap<Integer, Integer> simulations.Sugar.cellProportions ()
Definition at line 236 of file Sugar.java.
References simulations.Sim.calculateTotal().
void simulations.Sugar.fillAgents (List< Integer > index) private
Definition at line 64 of file Sugar.java.
References simulations.Sim.map, simulations.Sim.rand, utility.RandomRange.randInt(), simulations.Sim.setCell(), and simulations.Sim.size.
Referenced by simulations.Sugar.initMap().
void simulations.Sugar.growSugar (SceneUpdater updater) private
Definition at line 94 of file Sugar.java.
References simulations.Sugar.growBack, simulations.Sim.map, simulations.Sim.size, and cellsociety_team05.SceneUpdater.updateScene().
Referenced by simulations.Sugar.nextGen().
void simulations.Sugar.initMap ()
Definition at line 50 of file Sugar.java.
References simulations.Sugar.agentNum, simulations.Sim.cellTypes, simulations.Sugar.fillAgents(), simulations.Sim.populate(), simulations.Sim.rand, and simulations.Sim.size.
void simulations.Sugar.nextGen (SceneUpdater updater)
Definition at line 86 of file Sugar.java.
References simulations.Sugar.growSugar(), and simulations.Sugar.updateAgent().
void simulations.Sugar.setNewParams (HashMap< Integer, Integer > params)
Definition at line 243 of file Sugar.java.
String simulations.Sugar.simTitle ()
Definition at line 231 of file Sugar.java.
void simulations.Sugar.updateAgent (SceneUpdater updater) private
Definition at line 105 of file Sugar.java.
References utility.Agent.eat(), utility.Agent.ferSugar, utility.Agent.findNext(), utility.Neighborhood.getNeighbors(), utility.Agent.grow(), utility.Agent.life, utility.Agent.loc, simulations.Sim.map, utility.Agent.mate(), utility.Agent.mated, utility.Agent.meta, simulations.Sim.neighbors, simulations.Sim.rand, simulations.Sim.size, utility.Agent.sugar, simulations.Sugar.updateHash(), and utility.Agent.vision.
Referenced by simulations.Sugar.nextGen().
void simulations.Sugar.updateHash (Map< Integer, Integer > changedAgents, Map< Integer, Agent > babies, SceneUpdater updater) private
Definition at line 173 of file Sugar.java.
References utility.Agent.age, utility.Agent.ferSugar, utility.Agent.fertile, utility.Agent.life, utility.Agent.meta, simulations.Sim.rand, simulations.Sim.setCell(), simulations.Sim.size, utility.Agent.sugar, cellsociety_team05.SceneUpdater.updateScene(), and utility.Agent.vision.
Referenced by simulations.Sugar.updateAgent().
Member Data Documentation
int simulations.Sugar.agentNum = 0 private
Definition at line 22 of file Sugar.java.
Referenced by simulations.Sugar.initMap().
Map<Integer, Agent> simulations.Sugar.agents = new HashMap<Integer, Agent>() private
Definition at line 17 of file Sugar.java.
int [] simulations.Sugar.fertile private
Definition at line 27 of file Sugar.java.
Referenced by simulations.Sugar.Sugar().
int simulations.Sugar.growBack private
Definition at line 23 of file Sugar.java.
Referenced by simulations.Sugar.growSugar().
int simulations.Sugar.growInt private
Definition at line 24 of file Sugar.java.
int [] simulations.Sugar.initSugar private
Definition at line 19 of file Sugar.java.
int [] simulations.Sugar.maxLife private
Definition at line 26 of file Sugar.java.
Referenced by simulations.Sugar.Sugar().
int [] simulations.Sugar.metabolism private
Definition at line 20 of file Sugar.java.
int simulations.Sugar.patchCap
Definition at line 18 of file Sugar.java.
int simulations.Sugar.preset private
Definition at line 16 of file Sugar.java.
int [] simulations.Sugar.vision private
Definition at line 21 of file Sugar.java.
int simulations.Sugar.worldAge = 0 private
Definition at line 25 of file Sugar.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team05/repository/src/simulations/Sugar.java