cellsociety_team05: simulations.Sim Class Reference
simulations.Sim Class Reference abstract
Public Member Functions
Sim (int sim, int cellTypes, int size, int delay, int cellSides, List< Integer > params)
void initMap ()
SimData getData ()
HashMap< Pair, Pair > getMap ()
List< Integer > getParameters ()
abstract void setNewParams (HashMap< Integer, Integer > params)
abstract void nextGen (SceneUpdater updater)
abstract String simTitle ()
abstract HashMap< Integer, Integer > cellProportions ()
Protected Member Functions
List< Integer > getEmptyCells ()
void populate (int fill, int population, int size)
void setCell (int x, int y, int value)
int calculateTotal ()
Protected Attributes
int sim
List< Integer > params
SimData gameData
int[][] map
int delay
int cellTypes
int size
int cellSides
int[][] neighbors
Random rand = new Random()
Private Member Functions
void fillCell (int fill, int size)
boolean checkCell (int x, int y)
Detailed Description
Definition at line 13 of file Sim.java.
Constructor & Destructor Documentation
simulations.Sim.Sim (int sim, int cellTypes, int size, int delay, int cellSides, List< Integer > params)
Definition at line 26 of file Sim.java.
References simulations.Sim.cellSides, simulations.Sim.cellTypes, simulations.Sim.delay, simulations.Sim.params, simulations.Sim.sim, and simulations.Sim.size.
Member Function Documentation
int simulations.Sim.calculateTotal () protected
Definition at line 96 of file Sim.java.
Referenced by simulations.Life.cellProportions(), simulations.Fire.cellProportions(), simulations.Forage.cellProportions(), simulations.Wator.cellProportions(), simulations.Sugar.cellProportions(), simulations.Fire.Fire(), and simulations.Sugar.Sugar().
abstract HashMap<Integer, Integer> simulations.Sim.cellProportions () abstract
Referenced by cellsociety_team05.Master.evolve().
boolean simulations.Sim.checkCell (int x, int y) private
Definition at line 88 of file Sim.java.
Referenced by simulations.Sim.fillCell().
void simulations.Sim.fillCell (int fill, int size) private
Definition at line 77 of file Sim.java.
References simulations.Sim.checkCell(), and simulations.Sim.setCell().
Referenced by simulations.Sim.populate().
SimData simulations.Sim.getData ()
Definition at line 66 of file Sim.java.
References utility.MapCopier.copyOfArray(), simulations.Sim.delay, simulations.Sim.sim, and simulations.Sim.simTitle().
Referenced by cellsociety_team05.Master.init().
List<Integer> simulations.Sim.getEmptyCells () protected
Definition at line 37 of file Sim.java.
Referenced by simulations.Schelling.nextGen().
HashMap<Pair, Pair> simulations.Sim.getMap ()
Definition at line 73 of file Sim.java.
List<Integer> simulations.Sim.getParameters ()
Definition at line 100 of file Sim.java.
References simulations.Sim.params.
Referenced by cellsociety_team05.Master.init().
void simulations.Sim.initMap ()
Definition at line 50 of file Sim.java.
References simulations.Sim.cellTypes, and simulations.Sim.populate().
Referenced by cellsociety_team05.Master.init(), and cellsociety_team05.Initializer.setup().
abstract void simulations.Sim.nextGen (SceneUpdater updater) abstract
Referenced by cellsociety_team05.Master.evolve().
void simulations.Sim.populate (int fill, int population, int size) protected
Definition at line 58 of file Sim.java.
References simulations.Sim.fillCell().
Referenced by simulations.Wator.initMap(), simulations.Sim.initMap(), and simulations.Sugar.initMap().
void simulations.Sim.setCell (int x, int y, int value) protected
Definition at line 92 of file Sim.java.
Referenced by simulations.Sugar.fillAgents(), simulations.Sim.fillCell(), simulations.Forage.initMap(), and simulations.Sugar.updateHash().
abstract void simulations.Sim.setNewParams (HashMap< Integer, Integer > params) abstract
Referenced by cellsociety_team05.Master.evolve().
abstract String simulations.Sim.simTitle () abstract
Referenced by simulations.Sim.getData().
Member Data Documentation
int simulations.Sim.cellSides protected
Definition at line 21 of file Sim.java.
Referenced by simulations.Fire.checkFire(), simulations.Schelling.computeNeighbourhood(), simulations.Wator.findFish(), simulations.Wator.findTorroFish(), simulations.Forage.initMap(), and simulations.Sim.Sim().
int simulations.Sim.cellTypes protected
Definition at line 19 of file Sim.java.
Referenced by simulations.Sim.initMap(), simulations.Sugar.initMap(), and simulations.Sim.Sim().
int simulations.Sim.delay protected
Definition at line 18 of file Sim.java.
Referenced by simulations.Sim.getData(), and simulations.Sim.Sim().
SimData simulations.Sim.gameData protected
Definition at line 16 of file Sim.java.
int [][] simulations.Sim.map protected
Definition at line 17 of file Sim.java.
Referenced by simulations.Wator.cellNextGen(), simulations.Fire.checkFire(), simulations.Fire.checkTorroFire(), simulations.Life.computeNeighbourhood(), simulations.Schelling.computeNeighbourhood(), simulations.Schelling.computeTorrodialHood(), simulations.Sugar.fillAgents(), simulations.Wator.findFish(), simulations.Wator.findTorroFish(), simulations.Sugar.growSugar(), simulations.Wator.initMap(), simulations.Forage.moveAnt(), simulations.Life.nextGen(), simulations.Fire.nextGen(), simulations.Wator.nextGen(), simulations.Schelling.nextGen(), simulations.SlimeMold.nextGen(), simulations.SlimeMold.prepGrid(), simulations.Sugar.updateAgent(), simulations.Life.updateState(), simulations.Schelling.updateState(), and simulations.Fire.updateState().
int [][] simulations.Sim.neighbors protected
Definition at line 22 of file Sim.java.
Referenced by simulations.Fire.checkFire(), simulations.Fire.checkTorroFire(), simulations.Life.computeNeighbourhood(), simulations.Schelling.computeNeighbourhood(), simulations.Schelling.computeTorrodialHood(), simulations.Wator.findFish(), simulations.Wator.findTorroFish(), and simulations.Sugar.updateAgent().
List<Integer> simulations.Sim.params protected
Definition at line 15 of file Sim.java.
Referenced by simulations.Sim.getParameters(), simulations.Wator.initMap(), and simulations.Sim.Sim().
Random simulations.Sim.rand = new Random() protected
Definition at line 23 of file Sim.java.
Referenced by simulations.Wator.cellNextGen(), simulations.Sugar.fillAgents(), simulations.Sugar.initMap(), simulations.Forage.initMap(), simulations.Forage.moveAnt(), simulations.Forage.reproduce(), simulations.Sugar.updateAgent(), simulations.Sugar.updateHash(), and simulations.Fire.updateState().
int simulations.Sim.sim protected
Definition at line 14 of file Sim.java.
Referenced by simulations.Sim.getData(), and simulations.Sim.Sim().
int simulations.Sim.size protected
Definition at line 20 of file Sim.java.
Referenced by simulations.Sugar.fillAgents(), simulations.Forage.Forage(), simulations.Sugar.growSugar(), simulations.Sugar.initMap(), simulations.Forage.initMap(), simulations.Life.nextGen(), simulations.Sim.Sim(), simulations.Sugar.updateAgent(), and simulations.Sugar.updateHash().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team05/repository/src/simulations/Sim.java