cellsociety_team05: simulations.Fire Class Reference
simulations.Fire Class Reference
Public Member Functions
Fire (int sim, int cellTypes, int size, int delay, int cellSides, List< Integer > params)
void nextGen (SceneUpdater updater)
String simTitle ()
HashMap< Integer, Integer > cellProportions ()
void setNewParams (HashMap< Integer, Integer > params)
Public Member Functions inherited from simulations.Sim
Sim (int sim, int cellTypes, int size, int delay, int cellSides, List< Integer > params)
void initMap ()
SimData getData ()
HashMap< Pair, Pair > getMap ()
List< Integer > getParameters ()
abstract void setNewParams (HashMap< Integer, Integer > params)
abstract void nextGen (SceneUpdater updater)
abstract String simTitle ()
abstract HashMap< Integer, Integer > cellProportions ()
Private Member Functions
void checkFire (int row, int col, int[][] tempMap, List< Integer > burningTrees, SceneUpdater updater)
void checkTorroFire (int row, int col, int[][] tempMap, List< Integer > burningTrees, SceneUpdater updater)
int updateState (int row, int col, List< Integer > burningTrees)
Private Attributes
float fireProb
int fireTotal
int forestTotal
int burnedTotal
Additional Inherited Members
Protected Member Functions inherited from simulations.Sim
List< Integer > getEmptyCells ()
void populate (int fill, int population, int size)
void setCell (int x, int y, int value)
int calculateTotal ()
Protected Attributes inherited from simulations.Sim
int sim
List< Integer > params
SimData gameData
int[][] map
int delay
int cellTypes
int size
int cellSides
int[][] neighbors
Random rand = new Random()
Detailed Description
Definition at line 12 of file Fire.java.
Constructor & Destructor Documentation
simulations.Fire.Fire (int sim, int cellTypes, int size, int delay, int cellSides, List< Integer > params)
Definition at line 18 of file Fire.java.
References simulations.Sim.calculateTotal(), and simulations.Fire.fireTotal.
Member Function Documentation
HashMap<Integer, Integer> simulations.Fire.cellProportions ()
Definition at line 103 of file Fire.java.
References simulations.Sim.calculateTotal().
void simulations.Fire.checkFire (int row, int col, int tempMap[][], List< Integer > burningTrees, SceneUpdater updater) private
Definition at line 42 of file Fire.java.
References simulations.Sim.cellSides, utility.Neighborhood.getNeighbors(), simulations.Sim.map, simulations.Sim.neighbors, cellsociety_team05.SceneUpdater.updateScene(), and simulations.Fire.updateState().
void simulations.Fire.checkTorroFire (int row, int col, int tempMap[][], List< Integer > burningTrees, SceneUpdater updater) private
Definition at line 64 of file Fire.java.
References utility.Neighborhood.getTorroFire(), simulations.Sim.map, simulations.Sim.neighbors, cellsociety_team05.SceneUpdater.updateScene(), and simulations.Fire.updateState().
Referenced by simulations.Fire.nextGen().
void simulations.Fire.nextGen (SceneUpdater updater)
Definition at line 28 of file Fire.java.
References simulations.Fire.checkTorroFire(), utility.MapCopier.copyOfArray(), and simulations.Sim.map.
void simulations.Fire.setNewParams (HashMap< Integer, Integer > params)
Definition at line 113 of file Fire.java.
String simulations.Fire.simTitle ()
Definition at line 98 of file Fire.java.
int simulations.Fire.updateState (int row, int col, List< Integer > burningTrees) private
Definition at line 84 of file Fire.java.
References simulations.Sim.map, and simulations.Sim.rand.
Referenced by simulations.Fire.checkFire(), and simulations.Fire.checkTorroFire().
Member Data Documentation
int simulations.Fire.burnedTotal private
Definition at line 16 of file Fire.java.
float simulations.Fire.fireProb private
Definition at line 13 of file Fire.java.
int simulations.Fire.fireTotal private
Definition at line 14 of file Fire.java.
Referenced by simulations.Fire.Fire().
int simulations.Fire.forestTotal private
Definition at line 15 of file Fire.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team05/repository/src/simulations/Fire.java