cellsociety_team05: utility.Pheromone Class Reference
utility.Pheromone Class Reference
Public Member Functions
Pheromone (double evap, double diff, int max, int maxAnt, int cellSides, int size)
int[] selectFrontLoc (int[] coor, int[][] fronts, Random rand, int[][] antMap)
int[] selectSideLoc (int[] coor, int[][] sides, Random rand, int[][] antMap)
void topOffPhero (int row, int col, int[][] map)
void nextGen ()
void maxPhero (int i, int j)
Public Attributes
double[][] pheroMap
Private Attributes
double evapRate = 0.0001
double diffRate = 0.0001
int pheroLimit = 100
int maxAnt
int cellSides
Detailed Description
Definition at line 6 of file Pheromone.java.
Constructor & Destructor Documentation
utility.Pheromone.Pheromone (double evap, double diff, int max, int maxAnt, int cellSides, int size)
Definition at line 14 of file Pheromone.java.
References utility.Pheromone.cellSides, and utility.Pheromone.maxAnt.
Member Function Documentation
void utility.Pheromone.maxPhero (int i, int j)
Definition at line 113 of file Pheromone.java.
References utility.Pheromone.pheroLimit.
Referenced by simulations.Forage.initMap(), and simulations.Forage.moveAnt().
void utility.Pheromone.nextGen ()
Definition at line 93 of file Pheromone.java.
References utility.MapCopier.copyOfDoubleArray(), utility.Pheromone.diffRate, utility.Pheromone.evapRate, and utility.Neighborhood.getNeighbors().
Referenced by simulations.Forage.nextGen().
int [] utility.Pheromone.selectFrontLoc (int[] coor, int fronts[][], Random rand, int antMap[][])
Definition at line 24 of file Pheromone.java.
Referenced by simulations.Forage.moveAnt().
int [] utility.Pheromone.selectSideLoc (int[] coor, int sides[][], Random rand, int antMap[][])
Definition at line 50 of file Pheromone.java.
Referenced by simulations.Forage.moveAnt().
void utility.Pheromone.topOffPhero (int row, int col, int map[][])
Definition at line 76 of file Pheromone.java.
References utility.Neighborhood.getNeighbors().
Referenced by simulations.Forage.moveAnt().
Member Data Documentation
int utility.Pheromone.cellSides private
Definition at line 11 of file Pheromone.java.
Referenced by utility.Pheromone.Pheromone().
double utility.Pheromone.diffRate = 0.0001 private
Definition at line 8 of file Pheromone.java.
Referenced by utility.Pheromone.nextGen().
double utility.Pheromone.evapRate = 0.0001 private
Definition at line 7 of file Pheromone.java.
Referenced by utility.Pheromone.nextGen().
int utility.Pheromone.maxAnt private
Definition at line 10 of file Pheromone.java.
Referenced by utility.Pheromone.Pheromone().
int utility.Pheromone.pheroLimit = 100 private
Definition at line 9 of file Pheromone.java.
Referenced by utility.Pheromone.maxPhero().
double [][] utility.Pheromone.pheroMap
Definition at line 12 of file Pheromone.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team05/repository/src/utility/Pheromone.java