cellsociety_team05: cellsociety_team05.SceneUpdater Class Reference
cellsociety_team05.SceneUpdater Class Reference
Public Member Functions
SceneUpdater (Stage s, Timeline animation, int fps)
void newScene (SimData simData, List< Integer > params) throws Exception
void updateGraph (HashMap< Integer, Integer > cellProportions)
void updateScene (int i, int j, int state)
GUICreator returnGUI () throws Exception
HashMap< Integer, Integer > newParams ()
Package Attributes
HashMap< Integer, Color > stateColorMap = new HashMap<>()
LinkedList< Shape > indexMap = new LinkedList<Shape>()
Private Attributes
Stage s
int boardSizeK
int[][] map
Timeline ani
int fps
GUICreator gc
int type
AnimatedGraph ag
int count = 0
Static Private Attributes
static final int WIDTH_OF_WINDOW = 1200
static final int HEIGHT_OF_WINDOW = 600
Detailed Description
Definition at line 38 of file SceneUpdater.java.
Constructor & Destructor Documentation
cellsociety_team05.SceneUpdater.SceneUpdater (Stage s, Timeline animation, int fps)
Definition at line 53 of file SceneUpdater.java.
References cellsociety_team05.SceneUpdater.fps, and cellsociety_team05.SceneUpdater.s.
Member Function Documentation
HashMap<Integer, Integer> cellsociety_team05.SceneUpdater.newParams ()
Definition at line 134 of file SceneUpdater.java.
References animation.GUICreator.newParams.
Referenced by cellsociety_team05.Master.evolve().
void cellsociety_team05.SceneUpdater.newScene (SimData simData, List< Integer > params) throws Exception
Definition at line 59 of file SceneUpdater.java.
References animation.GUICreator.addButtonGrid(), utility.GridFiller.fill(), animation.GUICreator.fpsSlider(), animation.AnimatedGraph.init(), animation.GUICreator.paramLabels(), animation.GUICreator.paramSliders(), cellsociety_team05.SceneUpdater.returnGUI(), and utility.ColorPicker.setColors().
Referenced by cellsociety_team05.Master.init().
GUICreator cellsociety_team05.SceneUpdater.returnGUI () throws Exception
DUPLICATE CODE WITH READER CLASS - need to find a way to fix - Kei
Returns
Exceptions
Exception
Definition at line 106 of file SceneUpdater.java.
Referenced by cellsociety_team05.SceneUpdater.newScene().
void cellsociety_team05.SceneUpdater.updateGraph (HashMap< Integer, Integer > cellProportions)
Definition at line 86 of file SceneUpdater.java.
References animation.AnimatedGraph.addData().
Referenced by cellsociety_team05.Master.evolve().
void cellsociety_team05.SceneUpdater.updateScene (int i, int j, int state)
Definition at line 90 of file SceneUpdater.java.
Referenced by simulations.Wator.cellNextGen(), simulations.Fire.checkFire(), simulations.Fire.checkTorroFire(), simulations.Sugar.growSugar(), simulations.Forage.moveAnt(), simulations.Life.nextGen(), simulations.SlimeMold.nextGen(), simulations.Sugar.updateHash(), simulations.Wator.updateShark(), and simulations.Schelling.updateState().
Member Data Documentation
AnimatedGraph cellsociety_team05.SceneUpdater.ag private
Definition at line 50 of file SceneUpdater.java.
Timeline cellsociety_team05.SceneUpdater.ani private
Definition at line 46 of file SceneUpdater.java.
int cellsociety_team05.SceneUpdater.boardSizeK private
Definition at line 44 of file SceneUpdater.java.
int cellsociety_team05.SceneUpdater.count = 0 private
Definition at line 51 of file SceneUpdater.java.
int cellsociety_team05.SceneUpdater.fps private
Definition at line 47 of file SceneUpdater.java.
Referenced by cellsociety_team05.SceneUpdater.SceneUpdater().
GUICreator cellsociety_team05.SceneUpdater.gc private
Definition at line 48 of file SceneUpdater.java.
final int cellsociety_team05.SceneUpdater.HEIGHT_OF_WINDOW = 600 static private
Definition at line 42 of file SceneUpdater.java.
LinkedList<Shape> cellsociety_team05.SceneUpdater.indexMap = new LinkedList<Shape>() package
Definition at line 40 of file SceneUpdater.java.
int [][] cellsociety_team05.SceneUpdater.map private
Definition at line 45 of file SceneUpdater.java.
Stage cellsociety_team05.SceneUpdater.s private
Definition at line 43 of file SceneUpdater.java.
Referenced by cellsociety_team05.SceneUpdater.SceneUpdater().
HashMap<Integer, Color> cellsociety_team05.SceneUpdater.stateColorMap = new HashMap<>() package
Definition at line 39 of file SceneUpdater.java.
int cellsociety_team05.SceneUpdater.type private
Definition at line 49 of file SceneUpdater.java.
final int cellsociety_team05.SceneUpdater.WIDTH_OF_WINDOW = 1200 static private
Definition at line 41 of file SceneUpdater.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team05/repository/src/cellsociety_team05/SceneUpdater.java