cellsociety_team05: simulations.Wator Class Reference
simulations.Wator Class Reference
Public Member Functions
Wator (int sim, int cellTypes, int size, int delay, int cellSides, List< Integer > params)
void initMap ()
void nextGen (SceneUpdater updater)
String simTitle ()
HashMap< Integer, Integer > cellProportions ()
void setNewParams (HashMap< Integer, Integer > params)
Public Member Functions inherited from simulations.Sim
Sim (int sim, int cellTypes, int size, int delay, int cellSides, List< Integer > params)
void initMap ()
SimData getData ()
HashMap< Pair, Pair > getMap ()
List< Integer > getParameters ()
abstract void setNewParams (HashMap< Integer, Integer > params)
abstract void nextGen (SceneUpdater updater)
abstract String simTitle ()
abstract HashMap< Integer, Integer > cellProportions ()
Private Member Functions
void createFish (int length)
void updateShark (int row, int col, int[][] tempMap, List< Integer > deadFish, Neighborhood neighborhood, SceneUpdater updater)
Neighborhood findFish (int row, int col, List< Integer > deadFish, int[][] tempMap)
Neighborhood findTorroFish (int row, int col, List< Integer > deadFish, int[][] tempMap)
void cellNextGen (List< Integer > list, int[][] tempMap, List< Integer > deadFish, int row, int col, int nextHP, int type, SceneUpdater updater)
void updateFish (int row, int col, int[][] tempMap, List< Integer > deadFish, Neighborhood neighborhood, SceneUpdater updater)
Private Attributes
HashMap< Integer, Fish > fishMap = new HashMap<>()
int sharkHP
int fishHP
int lifeCycle
int fishCount
int sharkCount
Additional Inherited Members
Protected Member Functions inherited from simulations.Sim
List< Integer > getEmptyCells ()
void populate (int fill, int population, int size)
void setCell (int x, int y, int value)
int calculateTotal ()
Protected Attributes inherited from simulations.Sim
int sim
List< Integer > params
SimData gameData
int[][] map
int delay
int cellTypes
int size
int cellSides
int[][] neighbors
Random rand = new Random()
Detailed Description
Definition at line 12 of file Wator.java.
Constructor & Destructor Documentation
simulations.Wator.Wator (int sim, int cellTypes, int size, int delay, int cellSides, List< Integer > params)
Definition at line 20 of file Wator.java.
Member Function Documentation
void simulations.Wator.cellNextGen (List< Integer > list, int tempMap[][], List< Integer > deadFish, int row, int col, int nextHP, int type, SceneUpdater updater) private
Definition at line 138 of file Wator.java.
References simulations.Wator.lifeCycle, simulations.Sim.map, simulations.Sim.rand, and cellsociety_team05.SceneUpdater.updateScene().
Referenced by simulations.Wator.updateFish(), and simulations.Wator.updateShark().
HashMap<Integer, Integer> simulations.Wator.cellProportions ()
Definition at line 177 of file Wator.java.
References simulations.Sim.calculateTotal().
void simulations.Wator.createFish (int length) private
Definition at line 38 of file Wator.java.
Referenced by simulations.Wator.initMap().
Neighborhood simulations.Wator.findFish (int row, int col, List< Integer > deadFish, int tempMap[][]) private
Definition at line 97 of file Wator.java.
References simulations.Sim.cellSides, utility.Neighborhood.empty, utility.Neighborhood.fish, utility.Neighborhood.getNeighbors(), simulations.Sim.map, and simulations.Sim.neighbors.
Neighborhood simulations.Wator.findTorroFish (int row, int col, List< Integer > deadFish, int tempMap[][]) private
Definition at line 118 of file Wator.java.
References simulations.Sim.cellSides, utility.Neighborhood.empty, utility.Neighborhood.fish, utility.Neighborhood.getNeighbors(), simulations.Sim.map, and simulations.Sim.neighbors.
Referenced by simulations.Wator.nextGen().
void simulations.Wator.initMap ()
Definition at line 28 of file Wator.java.
References simulations.Wator.createFish(), simulations.Sim.map, simulations.Sim.params, and simulations.Sim.populate().
void simulations.Wator.nextGen (SceneUpdater updater)
Definition at line 46 of file Wator.java.
References utility.MapCopier.copyOfArray(), simulations.Wator.findTorroFish(), simulations.Sim.map, simulations.Wator.updateFish(), and simulations.Wator.updateShark().
void simulations.Wator.setNewParams (HashMap< Integer, Integer > params)
Definition at line 185 of file Wator.java.
String simulations.Wator.simTitle ()
Definition at line 172 of file Wator.java.
void simulations.Wator.updateFish (int row, int col, int tempMap[][], List< Integer > deadFish, Neighborhood neighborhood, SceneUpdater updater) private
Definition at line 163 of file Wator.java.
References simulations.Wator.cellNextGen(), and utility.Neighborhood.empty.
Referenced by simulations.Wator.nextGen().
void simulations.Wator.updateShark (int row, int col, int tempMap[][], List< Integer > deadFish, Neighborhood neighborhood, SceneUpdater updater) private
Definition at line 73 of file Wator.java.
References simulations.Wator.cellNextGen(), utility.Neighborhood.empty, utility.Neighborhood.fish, and cellsociety_team05.SceneUpdater.updateScene().
Referenced by simulations.Wator.nextGen().
Member Data Documentation
int simulations.Wator.fishCount private
Definition at line 17 of file Wator.java.
int simulations.Wator.fishHP private
Definition at line 15 of file Wator.java.
HashMap<Integer, Fish> simulations.Wator.fishMap = new HashMap<>() private
Definition at line 13 of file Wator.java.
int simulations.Wator.lifeCycle private
Definition at line 16 of file Wator.java.
Referenced by simulations.Wator.cellNextGen().
int simulations.Wator.sharkCount private
Definition at line 18 of file Wator.java.
int simulations.Wator.sharkHP private
Definition at line 13 of file Wator.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team05/repository/src/simulations/Wator.java