cellsociety_team05: simulations.Forage Class Reference
simulations.Forage Class Reference
Public Member Functions
Forage (int sim, int cellTypes, int size, int delay, int cellSides, List< Integer > params)
void initMap ()
void nextGen (SceneUpdater updater)
String simTitle ()
HashMap< Integer, Integer > cellProportions ()
void setNewParams (HashMap< Integer, Integer > params)
Public Member Functions inherited from simulations.Sim
Sim (int sim, int cellTypes, int size, int delay, int cellSides, List< Integer > params)
void initMap ()
SimData getData ()
HashMap< Pair, Pair > getMap ()
List< Integer > getParameters ()
abstract void setNewParams (HashMap< Integer, Integer > params)
abstract void nextGen (SceneUpdater updater)
abstract String simTitle ()
abstract HashMap< Integer, Integer > cellProportions ()
Public Attributes
int foraged
Private Member Functions
void reproduce ()
void moveAnt (SceneUpdater updater)
Private Attributes
int maxAnt
int[][] antMap
int[] nest = new int[2]
int[] food = new int[2]
int life
int worldAge = 0
int maxPhero
double evapRate
double diffRate
Map< Integer, Ant > ants = new HashMap<Integer, Ant>()
Pheromone homePh
Pheromone foodPh
Integer startAnt
int lifeCycle
int antPerGen
int antNum = 0
Additional Inherited Members
Protected Member Functions inherited from simulations.Sim
List< Integer > getEmptyCells ()
void populate (int fill, int population, int size)
void setCell (int x, int y, int value)
int calculateTotal ()
Protected Attributes inherited from simulations.Sim
int sim
List< Integer > params
SimData gameData
int[][] map
int delay
int cellTypes
int size
int cellSides
int[][] neighbors
Random rand = new Random()
Detailed Description
Definition at line 14 of file Forage.java.
Constructor & Destructor Documentation
simulations.Forage.Forage (int sim, int cellTypes, int size, int delay, int cellSides, List< Integer > params)
Definition at line 33 of file Forage.java.
References simulations.Sim.size.
Member Function Documentation
HashMap<Integer, Integer> simulations.Forage.cellProportions ()
Definition at line 151 of file Forage.java.
References simulations.Sim.calculateTotal().
void simulations.Forage.initMap ()
Definition at line 51 of file Forage.java.
References simulations.Sim.cellSides, utility.Pheromone.maxPhero(), simulations.Sim.rand, simulations.Sim.setCell(), simulations.Sim.size, and simulations.Forage.startAnt.
void simulations.Forage.moveAnt (SceneUpdater updater) private
Definition at line 84 of file Forage.java.
References simulations.Forage.antMap, utility.Ant.atFood(), utility.Ant.atHome(), utility.Ant.changeDir(), utility.Ant.coor, utility.Ant.getFrontNeighbors(), utility.Ant.getSideNeighbors(), utility.Ant.grow(), utility.Ant.hasFood, simulations.Sim.map, utility.Pheromone.maxPhero(), utility.Ant.moveTo(), simulations.Sim.rand, utility.Pheromone.selectFrontLoc(), utility.Pheromone.selectSideLoc(), utility.Pheromone.topOffPhero(), and cellsociety_team05.SceneUpdater.updateScene().
Referenced by simulations.Forage.nextGen().
void simulations.Forage.nextGen (SceneUpdater updater)
Definition at line 66 of file Forage.java.
References simulations.Forage.moveAnt(), utility.Pheromone.nextGen(), and simulations.Forage.reproduce().
void simulations.Forage.reproduce () private
Definition at line 76 of file Forage.java.
References simulations.Forage.antPerGen, and simulations.Sim.rand.
Referenced by simulations.Forage.nextGen().
void simulations.Forage.setNewParams (HashMap< Integer, Integer > params)
Definition at line 158 of file Forage.java.
String simulations.Forage.simTitle ()
Definition at line 146 of file Forage.java.
Member Data Documentation
int [][] simulations.Forage.antMap private
Definition at line 16 of file Forage.java.
Referenced by simulations.Forage.moveAnt().
int simulations.Forage.antNum = 0 private
Definition at line 31 of file Forage.java.
int simulations.Forage.antPerGen private
Definition at line 30 of file Forage.java.
Referenced by simulations.Forage.reproduce().
Map<Integer, Ant> simulations.Forage.ants = new HashMap<Integer, Ant>() private
Definition at line 24 of file Forage.java.
double simulations.Forage.diffRate private
Definition at line 23 of file Forage.java.
double simulations.Forage.evapRate private
Definition at line 22 of file Forage.java.
int [] simulations.Forage.food = new int[2] private
Definition at line 18 of file Forage.java.
Pheromone simulations.Forage.foodPh private
Definition at line 26 of file Forage.java.
int simulations.Forage.foraged
Definition at line 29 of file Forage.java.
Pheromone simulations.Forage.homePh private
Definition at line 25 of file Forage.java.
int simulations.Forage.life private
Definition at line 19 of file Forage.java.
int simulations.Forage.lifeCycle private
Definition at line 28 of file Forage.java.
int simulations.Forage.maxAnt private
Definition at line 15 of file Forage.java.
int simulations.Forage.maxPhero private
Definition at line 21 of file Forage.java.
int [] simulations.Forage.nest = new int[2] private
Definition at line 17 of file Forage.java.
Integer simulations.Forage.startAnt private
Definition at line 27 of file Forage.java.
Referenced by simulations.Forage.initMap().
int simulations.Forage.worldAge = 0 private
Definition at line 20 of file Forage.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team05/repository/src/simulations/Forage.java