cellsociety_team05: animation.GUICreator Class Reference
animation.GUICreator Class Reference abstract
Public Member Functions
GUICreator (Timeline animation, Stage s, int fps) throws Exception
GridPane fpsSlider ()
GridPane addButtonGrid ()
HashMap< Integer, Integer > newParams ()
abstract GridPane paramSliders (List< Integer > params)
abstract HashMap< Integer, String > paramLabels ()
Protected Member Functions
Group makeSlider (int min, int max, int value, int sliderX, int sliderY)
Protected Attributes
HashMap< Integer, Integer > newParams
Static Protected Attributes
static final int SIZE_OF_GRID = 600
static final int LOCATION_OF_PARAM_SLIDERS = 720
static final int Y_LOCATION_OF_SLIDER = 100
static final int LENGTH_OF_SLIDER = 250
static final int MIN_PERCENTAGE = 1
static final int MAX_PERCENTAGE = 100
Private Member Functions
void addPlayButton ()
void playAction (ActionEvent e)
void addPauseButton ()
void pauseAction (ActionEvent e)
void addloadXMLButton () throws Exception
void loadAction (ActionEvent e)
void addStepButton ()
void stepAction (ActionEvent e)
Private Attributes
Timeline animation
Button play
Button pause
Button load
Button step
Stage s
int fps
Static Private Attributes
static final int X_LOCATION_OF_FPS_SLIDER = 620
static final int Y_LOCATION_OF_FPS_SLIDER = 570
Detailed Description
Author
Kei Yoshikoshi The superclass that creates all of the GUI. This class creates all the Nodes and sets all the location and values. Subclasses include all the animation classes of the simulations.
Definition at line 26 of file GUICreator.java.
Constructor & Destructor Documentation
animation.GUICreator.GUICreator (Timeline animation, Stage s, int fps) throws Exception
Definition at line 44 of file GUICreator.java.
References animation.GUICreator.addButtonGrid(), animation.GUICreator.addloadXMLButton(), animation.GUICreator.addPauseButton(), animation.GUICreator.addPlayButton(), animation.GUICreator.addStepButton(), animation.GUICreator.animation, animation.GUICreator.fps, and animation.GUICreator.s.
Member Function Documentation
GridPane animation.GUICreator.addButtonGrid ()
Adds the different buttons to a GridPane
Returns
GridPane with the different buttons in them
Definition at line 213 of file GUICreator.java.
Referenced by animation.GUICreator.GUICreator(), and cellsociety_team05.SceneUpdater.newScene().
void animation.GUICreator.addloadXMLButton () throws Exception private
Creates a load button and sets its action.
Exceptions
Exception
Definition at line 99 of file GUICreator.java.
References animation.GUICreator.loadAction().
Referenced by animation.GUICreator.GUICreator().
void animation.GUICreator.addPauseButton () private
Creates a pause button and sets its action
Definition at line 80 of file GUICreator.java.
References animation.GUICreator.pauseAction().
Referenced by animation.GUICreator.GUICreator().
void animation.GUICreator.addPlayButton () private
Creates a play button and sets its action
Definition at line 60 of file GUICreator.java.
References animation.GUICreator.playAction().
Referenced by animation.GUICreator.GUICreator().
void animation.GUICreator.addStepButton () private
Creates a step button and sets its action.
Definition at line 123 of file GUICreator.java.
References animation.GUICreator.stepAction().
Referenced by animation.GUICreator.GUICreator().
GridPane animation.GUICreator.fpsSlider ()
Creates a slider to change FPS
Returns
GridPane that contains the FPS slider and label
Definition at line 145 of file GUICreator.java.
References animation.GUICreator.fps, and animation.GUICreator.makeSlider().
Referenced by cellsociety_team05.SceneUpdater.newScene().
void animation.GUICreator.loadAction (ActionEvent e) private
Sets the load action. Stops the animation and reinitiates the scene
Parameters
e
Definition at line 109 of file GUICreator.java.
References cellsociety_team05.Master.init().
Referenced by animation.GUICreator.addloadXMLButton().
Group animation.GUICreator.makeSlider (int min, int max, int value, int sliderX, int sliderY) protected
Takes in different parameters to create a slider
Parameters
min : Minimum value of the slider
max : Maximum value of the slider
value : The starting value of the slider
sliderX : The x-coordinate of the slider
sliderY : The y-coordinate of the slider
Returns
Definition at line 186 of file GUICreator.java.
Referenced by animation.GUICreator.fpsSlider(), animation.SchellingAnimation.paramSliders(), animation.FireAnimation.paramSliders(), animation.WatorAnimation.paramSliders(), and animation.ForageAnimation.paramSliders().
HashMap<Integer, Integer> animation.GUICreator.newParams ()
Returns the HashMap with the new parameters in them. Created to pass the map from front end to back end
Returns
Definition at line 229 of file GUICreator.java.
Referenced by animation.FireAnimation.paramSliders(), animation.SchellingAnimation.paramSliders(), animation.WatorAnimation.paramSliders(), and animation.ForageAnimation.paramSliders().
abstract HashMap<Integer, String> animation.GUICreator.paramLabels () abstract
Abstract method that creates a map that contains labels for cell types
Returns
: Map with labels for each cell type
Referenced by cellsociety_team05.SceneUpdater.newScene().
abstract GridPane animation.GUICreator.paramSliders (List< Integer > params) abstract
Abstract method that creates parameter sliders
Parameters
The different parameters that each simulation has
Returns
GridPane that contains the labels and sliders
Referenced by cellsociety_team05.SceneUpdater.newScene().
void animation.GUICreator.pauseAction (ActionEvent e) private
Sets the pause action. Stops the animation.
Parameters
e
Definition at line 90 of file GUICreator.java.
Referenced by animation.GUICreator.addPauseButton().
void animation.GUICreator.playAction (ActionEvent e) private
Sets the play action. Starts the animation and keeps it going indefinitely.
Parameters
e
Definition at line 72 of file GUICreator.java.
Referenced by animation.GUICreator.addPlayButton().
void animation.GUICreator.stepAction (ActionEvent e) private
Sets the step action. Stops the animation, sets the animation count to 1 (one frame) and plays it.
Parameters
e
Definition at line 134 of file GUICreator.java.
Referenced by animation.GUICreator.addStepButton().
Member Data Documentation
Timeline animation.GUICreator.animation private
Definition at line 35 of file GUICreator.java.
Referenced by animation.GUICreator.GUICreator().
int animation.GUICreator.fps private
Definition at line 41 of file GUICreator.java.
Referenced by animation.FireAnimation.FireAnimation(), animation.ForageAnimation.ForageAnimation(), animation.GUICreator.fpsSlider(), animation.GUICreator.GUICreator(), animation.LifeAnimation.LifeAnimation(), animation.SchellingAnimation.SchellingAnimation(), animation.SlimeMoldAnimation.SlimeMoldAnimation(), animation.SugarAnimation.SugarAnimation(), and animation.WatorAnimation.WatorAnimation().
final int animation.GUICreator.LENGTH_OF_SLIDER = 250 static protected
Definition at line 32 of file GUICreator.java.
Button animation.GUICreator.load private
Definition at line 38 of file GUICreator.java.
final int animation.GUICreator.LOCATION_OF_PARAM_SLIDERS = 720 static protected
Definition at line 28 of file GUICreator.java.
Referenced by animation.FireAnimation.paramSliders(), animation.SchellingAnimation.paramSliders(), animation.WatorAnimation.paramSliders(), and animation.ForageAnimation.paramSliders().
final int animation.GUICreator.MAX_PERCENTAGE = 100 static protected
Definition at line 34 of file GUICreator.java.
Referenced by animation.FireAnimation.paramSliders(), animation.SchellingAnimation.paramSliders(), and animation.WatorAnimation.paramSliders().
final int animation.GUICreator.MIN_PERCENTAGE = 1 static protected
Definition at line 33 of file GUICreator.java.
Referenced by animation.FireAnimation.paramSliders(), animation.SchellingAnimation.paramSliders(), animation.WatorAnimation.paramSliders(), and animation.ForageAnimation.paramSliders().
HashMap<Integer, Integer> animation.GUICreator.newParams protected
Definition at line 42 of file GUICreator.java.
Referenced by cellsociety_team05.SceneUpdater.newParams().
Button animation.GUICreator.pause private
Definition at line 37 of file GUICreator.java.
Button animation.GUICreator.play private
Definition at line 36 of file GUICreator.java.
Stage animation.GUICreator.s private
Definition at line 40 of file GUICreator.java.
Referenced by animation.FireAnimation.FireAnimation(), animation.ForageAnimation.ForageAnimation(), animation.GUICreator.GUICreator(), animation.LifeAnimation.LifeAnimation(), animation.SchellingAnimation.paramSliders(), animation.FireAnimation.paramSliders(), animation.WatorAnimation.paramSliders(), animation.ForageAnimation.paramSliders(), animation.SchellingAnimation.SchellingAnimation(), animation.SlimeMoldAnimation.SlimeMoldAnimation(), animation.SugarAnimation.SugarAnimation(), and animation.WatorAnimation.WatorAnimation().
final int animation.GUICreator.SIZE_OF_GRID = 600 static protected
Definition at line 27 of file GUICreator.java.
Referenced by animation.FireAnimation.paramSliders(), animation.SchellingAnimation.paramSliders(), animation.WatorAnimation.paramSliders(), and animation.ForageAnimation.paramSliders().
Button animation.GUICreator.step private
Definition at line 39 of file GUICreator.java.
final int animation.GUICreator.X_LOCATION_OF_FPS_SLIDER = 620 static private
Definition at line 29 of file GUICreator.java.
final int animation.GUICreator.Y_LOCATION_OF_FPS_SLIDER = 570 static private
Definition at line 30 of file GUICreator.java.
final int animation.GUICreator.Y_LOCATION_OF_SLIDER = 100 static protected
Definition at line 31 of file GUICreator.java.
Referenced by animation.FireAnimation.paramSliders(), animation.SchellingAnimation.paramSliders(), animation.WatorAnimation.paramSliders(), and animation.ForageAnimation.paramSliders().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team05/repository/src/animation/GUICreator.java