cellsociety_team05: utility.Neighborhood Class Reference
utility.Neighborhood Class Reference
Static Public Member Functions
static int[][] getNeighbors (int cellSides, int col, int neighborNum)
static int[][] getTorroFire ()
static int[][] getTorrodialNeighbors ()
static int[][] getAntNeighbors (int cellSides, int col, int dir)
Public Attributes
List< Integer > fish = new ArrayList<Integer>()
List< Integer > empty = new ArrayList<Integer>()
Static Public Attributes
static final int[][] hexneighbors_1
static final int[][] hexneighbors_2
static final int[][] normal8neighbors
static final int[][] normal4neighbors
static final int[][][] antNeighbors
static final int[][][] antHexNeighbors_1
static final int[][][] antHexNeighbors_2
Detailed Description
Definition at line 6 of file Neighborhood.java.
Member Function Documentation
static int [][] utility.Neighborhood.getAntNeighbors (int cellSides, int col, int dir) static
Definition at line 50 of file Neighborhood.java.
static int [][] utility.Neighborhood.getNeighbors (int cellSides, int col, int neighborNum) static
Definition at line 30 of file Neighborhood.java.
References utility.Neighborhood.hexneighbors_1, utility.Neighborhood.hexneighbors_2, utility.Neighborhood.normal4neighbors, and utility.Neighborhood.normal8neighbors.
Referenced by simulations.Fire.checkFire(), simulations.Schelling.computeNeighbourhood(), simulations.Wator.findFish(), simulations.Wator.findTorroFish(), utility.Agent.hasEmptyPatch(), utility.Pheromone.nextGen(), utility.Pheromone.topOffPhero(), and simulations.Sugar.updateAgent().
static int [][] utility.Neighborhood.getTorrodialNeighbors () static
Definition at line 46 of file Neighborhood.java.
References utility.Neighborhood.normal8neighbors.
Referenced by simulations.Life.computeNeighbourhood(), and simulations.Schelling.computeTorrodialHood().
static int [][] utility.Neighborhood.getTorroFire () static
Definition at line 42 of file Neighborhood.java.
References utility.Neighborhood.normal4neighbors.
Referenced by simulations.Fire.checkTorroFire().
Member Data Documentation
final int [][][] utility.Neighborhood.antHexNeighbors_1 static
Initial value:
= {
            { { 0, -1 }, { -1, 0 }, { 0, 1 } }, { { 0, 1 }, { 1, 1 } },
            { { 1, -1 }, { 1, 0 }, { 1, 1 } }, { { 0, -1 }, { 1, -1 } } }
Definition at line 21 of file Neighborhood.java.
final int [][][] utility.Neighborhood.antHexNeighbors_2 static
Initial value:
= {
            { { -1, -1 }, { -1, 0 }, { -1, 1 } }, { { -1, 1 }, { 0, 1 } },
            { { 0, -1 }, { 1, 0 }, { 0, 1 } }, { { -1, -1 }, { 0, -1 } } }
Definition at line 24 of file Neighborhood.java.
final int [][][] utility.Neighborhood.antNeighbors static
Initial value:
= {
            { { -1, -1 }, { -1, 0 }, { -1, 1 } },
            { { -1, 1 }, { 0, 1 }, { 1, 1 } },
            { { 1, -1 }, { 1, 0 }, { 1, 1 } },
            { { 1, -1 }, { 0, -1 }, { -1, -1 } } }
Definition at line 16 of file Neighborhood.java.
List<Integer> utility.Neighborhood.empty = new ArrayList<Integer>()
Definition at line 28 of file Neighborhood.java.
Referenced by simulations.Wator.findFish(), simulations.Wator.findTorroFish(), simulations.Wator.updateFish(), and simulations.Wator.updateShark().
List<Integer> utility.Neighborhood.fish = new ArrayList<Integer>()
Definition at line 27 of file Neighborhood.java.
Referenced by simulations.Wator.findFish(), simulations.Wator.findTorroFish(), and simulations.Wator.updateShark().
final int [][] utility.Neighborhood.hexneighbors_1 static
Initial value:
= { { 0, 1 }, { 0, -1 },
            { -1, 0 }, { 1, -1 }, { 1, 0 }, { 1, 1 } }
Definition at line 7 of file Neighborhood.java.
Referenced by utility.Neighborhood.getNeighbors().
final int [][] utility.Neighborhood.hexneighbors_2 static
Initial value:
= { { 0, 1 }, { 0, -1 },
            { -1, 0 }, { -1, -1 }, { 1, 0 }, { -1, 1 } }
Definition at line 9 of file Neighborhood.java.
Referenced by utility.Neighborhood.getNeighbors().
final int [][] utility.Neighborhood.normal4neighbors static
Initial value:
= { { 0, 1 }, { 0, -1 },
            { 1, 0 }, { -1, 0 } }
Definition at line 13 of file Neighborhood.java.
Referenced by utility.Neighborhood.getNeighbors(), and utility.Neighborhood.getTorroFire().
final int [][] utility.Neighborhood.normal8neighbors static
Initial value:
= { { 1, 1 }, { -1, -1 },
            { 1, -1 }, { -1, 1 }, { 0, 1 }, { 0, -1 }, { 1, 0 }, { -1, 0 } }
Definition at line 11 of file Neighborhood.java.
Referenced by utility.Neighborhood.getNeighbors(), and utility.Neighborhood.getTorrodialNeighbors().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team05/repository/src/utility/Neighborhood.java