cellsociety_team05: utility.Agent Class Reference
utility.Agent Class Reference
Public Member Functions
Agent (int[] iniSugar, int[] vis, int[] met, Random rand, int[] loc, int preset, int size)
Agent (int iniSugar, int vis, int met, Random rand, int[] loc, int preset, int size, int maxLife, int[] fertile)
Agent (int iniSugar, int vis, int met, int age, int ferSu, Random rand, int[] loc, int preset, int size, int maxLife, int[] fertile)
Agent (int[] iniSugar, int[] vis, int[] met, Random rand, int[] loc, int preset, int size, int[] maxLife, int[] fertile)
int[] findNext (int[][] map, Random rand)
void eat (int sugar)
boolean grow ()
void moveTo (int[] next)
Integer mate (Agent thisAgent, int[][] map, Random rand, Map< Integer, Agent > babies)
int getIndex ()
Public Attributes
int age = 0
int gender
int vision
int sugar
int ferSugar
int life
int meta
int[] loc
int[] fertile
ArrayList< Integer > mated = new ArrayList<Integer>()
Private Member Functions
List< Integer > hasEmptyPatch (int[][] map)
boolean hungry ()
boolean active ()
Private Attributes
int size
int preset
Detailed Description
Definition at line 9 of file Agent.java.
Constructor & Destructor Documentation
utility.Agent.Agent (int[] iniSugar, int[] vis, int[] met, Random rand, int[] loc, int preset, int size)
Definition at line 23 of file Agent.java.
References utility.Agent.loc, utility.Agent.preset, utility.RandomRange.randInt(), utility.Agent.size, and utility.Agent.sugar.
utility.Agent.Agent (int iniSugar, int vis, int met, Random rand, int[] loc, int preset, int size, int maxLife, int[] fertile)
Definition at line 34 of file Agent.java.
References utility.Agent.fertile, utility.Agent.loc, utility.Agent.preset, utility.Agent.size, and utility.Agent.sugar.
utility.Agent.Agent (int iniSugar, int vis, int met, int age, int ferSu, Random rand, int[] loc, int preset, int size, int maxLife, int[] fertile)
Definition at line 48 of file Agent.java.
References utility.Agent.age, utility.Agent.fertile, utility.Agent.loc, utility.Agent.preset, and utility.Agent.size.
utility.Agent.Agent (int[] iniSugar, int[] vis, int[] met, Random rand, int[] loc, int preset, int size, int[] maxLife, int[] fertile)
Definition at line 64 of file Agent.java.
References utility.Agent.fertile, utility.Agent.loc, utility.Agent.preset, utility.RandomRange.randInt(), utility.Agent.size, and utility.Agent.sugar.
Member Function Documentation
boolean utility.Agent.active () private
Definition at line 197 of file Agent.java.
Referenced by utility.Agent.mate().
void utility.Agent.eat (int sugar)
Definition at line 119 of file Agent.java.
References utility.Agent.sugar.
Referenced by simulations.Sugar.updateAgent().
int [] utility.Agent.findNext (int map[][], Random rand)
Definition at line 78 of file Agent.java.
References utility.Agent.vision.
Referenced by simulations.Sugar.updateAgent().
int utility.Agent.getIndex ()
Definition at line 173 of file Agent.java.
Referenced by utility.Agent.mate().
boolean utility.Agent.grow ()
Definition at line 123 of file Agent.java.
References utility.Agent.meta.
Referenced by simulations.Sugar.updateAgent().
List<Integer> utility.Agent.hasEmptyPatch (int map[][]) private
Definition at line 178 of file Agent.java.
References utility.Neighborhood.getNeighbors().
Referenced by utility.Agent.mate().
boolean utility.Agent.hungry () private
Definition at line 193 of file Agent.java.
References utility.Agent.ferSugar.
Referenced by utility.Agent.mate().
Integer utility.Agent.mate (Agent thisAgent, int map[][], Random rand, Map< Integer, Agent > babies)
Definition at line 143 of file Agent.java.
References utility.Agent.active(), utility.Agent.gender, utility.Agent.getIndex(), utility.Agent.hasEmptyPatch(), utility.Agent.hungry(), and utility.Agent.mated.
Referenced by simulations.Sugar.updateAgent().
void utility.Agent.moveTo (int[] next)
Definition at line 139 of file Agent.java.
Member Data Documentation
int utility.Agent.age = 0
Definition at line 10 of file Agent.java.
Referenced by utility.Agent.Agent(), and simulations.Sugar.updateHash().
int utility.Agent.ferSugar
Definition at line 15 of file Agent.java.
Referenced by utility.Agent.hungry(), simulations.Sugar.updateAgent(), and simulations.Sugar.updateHash().
int [] utility.Agent.fertile
Definition at line 19 of file Agent.java.
Referenced by utility.Agent.Agent(), and simulations.Sugar.updateHash().
int utility.Agent.gender
Definition at line 12 of file Agent.java.
Referenced by utility.Agent.mate().
int utility.Agent.life
Definition at line 16 of file Agent.java.
Referenced by simulations.Sugar.updateAgent(), and simulations.Sugar.updateHash().
int [] utility.Agent.loc
Definition at line 18 of file Agent.java.
Referenced by utility.Agent.Agent(), and simulations.Sugar.updateAgent().
ArrayList<Integer> utility.Agent.mated = new ArrayList<Integer>()
Definition at line 21 of file Agent.java.
Referenced by utility.Agent.mate(), and simulations.Sugar.updateAgent().
int utility.Agent.meta
Definition at line 17 of file Agent.java.
Referenced by utility.Agent.grow(), simulations.Sugar.updateAgent(), and simulations.Sugar.updateHash().
int utility.Agent.preset private
Definition at line 20 of file Agent.java.
Referenced by utility.Agent.Agent().
int utility.Agent.size private
Definition at line 11 of file Agent.java.
Referenced by utility.Agent.Agent().
int utility.Agent.sugar
Definition at line 14 of file Agent.java.
Referenced by utility.Agent.Agent(), utility.Agent.eat(), simulations.Sugar.updateAgent(), and simulations.Sugar.updateHash().
int utility.Agent.vision
Definition at line 13 of file Agent.java.
Referenced by utility.Agent.findNext(), simulations.Sugar.updateAgent(), and simulations.Sugar.updateHash().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team05/repository/src/utility/Agent.java