cellsociety_team05: animation.AnimatedGraph Class Reference
animation.AnimatedGraph Class Reference
Public Member Functions
AnimatedGraph (HashMap< Integer, String > paramLabels)
Pane init ()
void addData (int count, HashMap< Integer, Integer > proportions)
Package Attributes
HashMap< Integer, String > paramLabels
HashMap< Integer, XYChart.Series > seriesMap
Private Member Functions
HashMap< Integer, XYChart.Series > createAddSeries (HashMap< Integer, String > paramLabels)
Static Private Attributes
static final int MAX_PERCENTAGE = 100
static final int MIN_PERCENTAGE = 0
static final int TICK_UNIT = 10
static final int GRID_SIZE = 600
static final int GRAPH_Y_LOCATION = 180
Detailed Description
Author
Kei Yoshikoshi A class that creates a line chart that plots the different cell proportions per frame
Definition at line 18 of file AnimatedGraph.java.
Constructor & Destructor Documentation
animation.AnimatedGraph.AnimatedGraph (HashMap< Integer, String > paramLabels)
Definition at line 28 of file AnimatedGraph.java.
References animation.AnimatedGraph.paramLabels.
Member Function Documentation
void animation.AnimatedGraph.addData (int count, HashMap< Integer, Integer > proportions)
Adds data to each cell type at each frame
Parameters
count : the frame
proportions : HashMap that maps the index to the cell proportion at the specific frame
Definition at line 105 of file AnimatedGraph.java.
References animation.AnimatedGraph.seriesMap.
Referenced by cellsociety_team05.SceneUpdater.updateGraph().
HashMap<Integer, XYChart.Series> animation.AnimatedGraph.createAddSeries (HashMap< Integer, String > paramLabels) private
Creates XYChart.series with certain labels given the index
Parameters
paramLabels : HashMap that contains the index and the label
Returns
HashMap that contains the index and XYChart.Series
Definition at line 40 of file AnimatedGraph.java.
References animation.AnimatedGraph.seriesMap.
Referenced by animation.AnimatedGraph.init().
Pane animation.AnimatedGraph.init ()
Creates a LineChart that plots percentage of certain cells vs. frame
Returns
Pane that includes the LineChart
Definition at line 57 of file AnimatedGraph.java.
References animation.AnimatedGraph.createAddSeries(), and animation.AnimatedGraph.seriesMap.
Referenced by cellsociety_team05.SceneUpdater.newScene().
Member Data Documentation
final int animation.AnimatedGraph.GRAPH_Y_LOCATION = 180 static private
Definition at line 23 of file AnimatedGraph.java.
final int animation.AnimatedGraph.GRID_SIZE = 600 static private
Definition at line 22 of file AnimatedGraph.java.
final int animation.AnimatedGraph.MAX_PERCENTAGE = 100 static private
Definition at line 19 of file AnimatedGraph.java.
final int animation.AnimatedGraph.MIN_PERCENTAGE = 0 static private
Definition at line 20 of file AnimatedGraph.java.
HashMap<Integer, String> animation.AnimatedGraph.paramLabels package
Definition at line 24 of file AnimatedGraph.java.
Referenced by animation.AnimatedGraph.AnimatedGraph().
HashMap<Integer, XYChart.Series> animation.AnimatedGraph.seriesMap package
Definition at line 26 of file AnimatedGraph.java.
Referenced by animation.AnimatedGraph.addData(), animation.AnimatedGraph.createAddSeries(), and animation.AnimatedGraph.init().
final int animation.AnimatedGraph.TICK_UNIT = 10 static private
Definition at line 21 of file AnimatedGraph.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team05/repository/src/animation/AnimatedGraph.java