cellsociety_team05: simulations.SlimeMold Class Reference
simulations.SlimeMold Class Reference
Classes
class SlimeBox
class SlimeCell
Public Member Functions
SlimeMold (int game, int cellTypes, int size, int fps, int cellSides, List< Integer > params)
void nextGen (SceneUpdater updater)
HashMap< Integer, SlimeBox > updateTerrain (HashMap< Integer, SlimeCell > cellsNext, HashMap< Integer, SlimeBox > terrain, int row, int col, int[][] tempMap)
HashMap< Integer, SlimeCell > updateCells (HashMap< Integer, SlimeCell > cells, HashMap< Integer, SlimeBox > terrain)
int whereNext (SlimeCell cell, HashMap< Integer, SlimeBox > terrainXY)
String simTitle ()
HashMap< Integer, Integer > cellProportions ()
void setNewParams (HashMap< Integer, Integer > params)
Public Member Functions inherited from simulations.Sim
Sim (int sim, int cellTypes, int size, int delay, int cellSides, List< Integer > params)
void initMap ()
SimData getData ()
HashMap< Pair, Pair > getMap ()
List< Integer > getParameters ()
abstract void setNewParams (HashMap< Integer, Integer > params)
abstract void nextGen (SceneUpdater updater)
abstract String simTitle ()
abstract HashMap< Integer, Integer > cellProportions ()
Public Attributes
final int boardLength = 100
Private Member Functions
void prepGrid (int[][] tempMap)
Private Attributes
HashMap< Integer, SlimeBox > terrain = new HashMap<Integer, SlimeMold.SlimeBox>()
HashMap< Integer, SlimeCell > cells = new HashMap<Integer, SlimeMold.SlimeCell>()
int evaporationRate
Additional Inherited Members
Protected Member Functions inherited from simulations.Sim
List< Integer > getEmptyCells ()
void populate (int fill, int population, int size)
void setCell (int x, int y, int value)
int calculateTotal ()
Protected Attributes inherited from simulations.Sim
int sim
List< Integer > params
SimData gameData
int[][] map
int delay
int cellTypes
int size
int cellSides
int[][] neighbors
Random rand = new Random()
Detailed Description
Definition at line 11 of file SlimeMold.java.
Constructor & Destructor Documentation
simulations.SlimeMold.SlimeMold (int game, int cellTypes, int size, int fps, int cellSides, List< Integer > params)
Definition at line 52 of file SlimeMold.java.
Member Function Documentation
HashMap<Integer, Integer> simulations.SlimeMold.cellProportions ()
Definition at line 211 of file SlimeMold.java.
void simulations.SlimeMold.nextGen (SceneUpdater updater)
Definition at line 75 of file SlimeMold.java.
References utility.MapCopier.copyOfArray(), simulations.Sim.map, simulations.SlimeMold.prepGrid(), simulations.SlimeMold.updateCells(), cellsociety_team05.SceneUpdater.updateScene(), and simulations.SlimeMold.updateTerrain().
void simulations.SlimeMold.prepGrid (int tempMap[][]) private
Definition at line 58 of file SlimeMold.java.
References simulations.Sim.map.
Referenced by simulations.SlimeMold.nextGen().
void simulations.SlimeMold.setNewParams (HashMap< Integer, Integer > params)
Definition at line 217 of file SlimeMold.java.
String simulations.SlimeMold.simTitle ()
Definition at line 206 of file SlimeMold.java.
HashMap<Integer, SlimeCell> simulations.SlimeMold.updateCells (HashMap< Integer, SlimeCell > cells, HashMap< Integer, SlimeBox > terrain)
Definition at line 117 of file SlimeMold.java.
References simulations.SlimeMold.SlimeCell.coord, simulations.SlimeMold.SlimeCell.depositAmt, simulations.SlimeMold.SlimeCell.facing, simulations.SlimeMold.SlimeBox.pheromone, simulations.SlimeMold.SlimeCell.sniffAngle, simulations.SlimeMold.SlimeCell.sniffThreshhold, and simulations.SlimeMold.whereNext().
Referenced by simulations.SlimeMold.nextGen().
HashMap<Integer, SlimeBox> simulations.SlimeMold.updateTerrain (HashMap< Integer, SlimeCell > cellsNext, HashMap< Integer, SlimeBox > terrain, int row, int col, int tempMap[][])
Definition at line 89 of file SlimeMold.java.
References simulations.SlimeMold.boardLength, simulations.SlimeMold.SlimeBox.containsCell, simulations.SlimeMold.SlimeBox.evaporationRate, and simulations.SlimeMold.SlimeBox.pheromone.
Referenced by simulations.SlimeMold.nextGen().
int simulations.SlimeMold.whereNext (SlimeCell cell, HashMap< Integer, SlimeBox > terrainXY)
Definition at line 147 of file SlimeMold.java.
References simulations.SlimeMold.boardLength, simulations.SlimeMold.SlimeBox.containsCell, simulations.SlimeMold.SlimeBox.coord, simulations.SlimeMold.SlimeCell.coord, simulations.SlimeMold.SlimeCell.facing, and simulations.SlimeMold.SlimeBox.pheromone.
Referenced by simulations.SlimeMold.updateCells().
Member Data Documentation
final int simulations.SlimeMold.boardLength = 100
Definition at line 13 of file SlimeMold.java.
Referenced by simulations.SlimeMold.updateTerrain(), and simulations.SlimeMold.whereNext().
HashMap<Integer, SlimeCell> simulations.SlimeMold.cells = new HashMap<Integer, SlimeMold.SlimeCell>() private
Definition at line 49 of file SlimeMold.java.
int simulations.SlimeMold.evaporationRate private
Definition at line 50 of file SlimeMold.java.
HashMap<Integer, SlimeBox> simulations.SlimeMold.terrain = new HashMap<Integer, SlimeMold.SlimeBox>() private
Definition at line 48 of file SlimeMold.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team05/repository/src/simulations/SlimeMold.java