cellsociety_team05: utility.Ant Class Reference
utility.Ant Class Reference
Public Member Functions
Ant (Random rand, int life, int[] nestCoor)
void changeDir (int[] next)
int[][] getFrontNeighbors ()
boolean grow ()
int[][] getSideNeighbors ()
void moveTo (int[] coor)
int atHome ()
void atFood ()
Public Attributes
int dir
int[] coor
boolean hasFood = false
Private Attributes
int age = 0
int life
final int[][] directions
int foraged = 0
Detailed Description
Definition at line 5 of file Ant.java.
Constructor & Destructor Documentation
utility.Ant.Ant (Random rand, int life, int[] nestCoor)
Definition at line 15 of file Ant.java.
References utility.Ant.life.
Member Function Documentation
void utility.Ant.atFood ()
Definition at line 105 of file Ant.java.
Referenced by simulations.Forage.moveAnt().
int utility.Ant.atHome ()
Definition at line 96 of file Ant.java.
Referenced by simulations.Forage.moveAnt().
void utility.Ant.changeDir (int[] next)
Definition at line 21 of file Ant.java.
Referenced by simulations.Forage.moveAnt().
int [][] utility.Ant.getFrontNeighbors ()
Definition at line 35 of file Ant.java.
References utility.Ant.dir.
Referenced by simulations.Forage.moveAnt().
int [][] utility.Ant.getSideNeighbors ()
Definition at line 64 of file Ant.java.
References utility.Ant.dir.
Referenced by simulations.Forage.moveAnt().
boolean utility.Ant.grow ()
Definition at line 55 of file Ant.java.
Referenced by simulations.Forage.moveAnt().
void utility.Ant.moveTo (int[] coor)
Definition at line 92 of file Ant.java.
References utility.Ant.coor.
Referenced by simulations.Forage.moveAnt().
Member Data Documentation
int utility.Ant.age = 0 private
Definition at line 6 of file Ant.java.
int [] utility.Ant.coor
Definition at line 11 of file Ant.java.
Referenced by simulations.Forage.moveAnt(), and utility.Ant.moveTo().
int utility.Ant.dir
Definition at line 8 of file Ant.java.
Referenced by utility.Ant.getFrontNeighbors(), and utility.Ant.getSideNeighbors().
final int [][] utility.Ant.directions private
Initial value:
= { { -1, 0 }, { 0, 1 }, { 1, 0 },
            { 0, -1 } }
Definition at line 9 of file Ant.java.
int utility.Ant.foraged = 0 private
Definition at line 13 of file Ant.java.
boolean utility.Ant.hasFood = false
Definition at line 12 of file Ant.java.
Referenced by simulations.Forage.moveAnt().
int utility.Ant.life private
Definition at line 7 of file Ant.java.
Referenced by utility.Ant.Ant().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team05/repository/src/utility/Ant.java