cellsociety_team05: cellsociety_team05.Master Class Reference
cellsociety_team05.Master Class Reference
Public Member Functions
void init (Stage s) throws FileNotFoundException, NullPointerException
KeyFrame addKeyFrame (int frameRate)
void play ()
Private Member Functions
void evolve (ActionEvent e)
Private Attributes
int fps = 10
Timeline animation = new Timeline()
Sim sim
SceneUpdater updater
KeyFrame frame
Detailed Description
Definition at line 18 of file Master.java.
Member Function Documentation
KeyFrame cellsociety_team05.Master.addKeyFrame (int frameRate)
Definition at line 50 of file Master.java.
References cellsociety_team05.Master.evolve().
Referenced by cellsociety_team05.Master.play().
void cellsociety_team05.Master.evolve (ActionEvent e) private
Definition at line 54 of file Master.java.
References simulations.Sim.cellProportions(), cellsociety_team05.SceneUpdater.newParams(), simulations.Sim.nextGen(), simulations.Sim.setNewParams(), and cellsociety_team05.SceneUpdater.updateGraph().
Referenced by cellsociety_team05.Master.addKeyFrame().
void cellsociety_team05.Master.init (Stage s) throws FileNotFoundException, NullPointerException
Definition at line 25 of file Master.java.
References simulations.Sim.getData(), simulations.Sim.getParameters(), simulations.Sim.initMap(), cellsociety_team05.SceneUpdater.newScene(), cellsociety_team05.Master.play(), cellsociety_team05.Initializer.readXML(), error.XMLNotFoundException.returnDefaultSim(), cellsociety_team05.Initializer.setup(), and utility.SimData.simFPS().
Referenced by animation.GUICreator.loadAction(), and cellsociety_team05.Main.start().
void cellsociety_team05.Master.play ()
Definition at line 63 of file Master.java.
References cellsociety_team05.Master.addKeyFrame().
Referenced by cellsociety_team05.Master.init().
Member Data Documentation
Timeline cellsociety_team05.Master.animation = new Timeline() private
Definition at line 20 of file Master.java.
int cellsociety_team05.Master.fps = 10 private
Definition at line 19 of file Master.java.
KeyFrame cellsociety_team05.Master.frame private
Definition at line 23 of file Master.java.
Sim cellsociety_team05.Master.sim private
Definition at line 21 of file Master.java.
SceneUpdater cellsociety_team05.Master.updater private
Definition at line 22 of file Master.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team05/repository/src/cellsociety_team05/Master.java